### PR TITLE
Improve README

### PR DESCRIPTION
**Pull request by odegroot**
Context: #135

You said you're not so good at English, but I actually thought it's already mostly fine. Perfectly understandable; I only have minor improvements here and there.

To me, it was not so clear what to expect from the appservice-acmebot before deploying it, so I added a diagram. I hope you like it.

I also mentioned the REST API, since I used it to automate the issuance of certificates.

### CODE REVIEW

**Comment by shibayan** [comment]
Thank you for the great improvement in documentation.

The creation of the diagram is much appreciated. Perhaps the link to the image is broken and does not appear, could you convert it to PNG and change it to the link you uploaded?
To upload images, drop them in the comments of this PR and a link to GitHub will be created, so use it.

**Comment by odegroot** [comment]
> Perhaps the link to the image is broken and does not appear

Oh, that is strange - the svg _does_ appear when I view the readme on my fork.
Demo: https://github.com/odegroot/appservice-acmebot/tree/docs

I see that the image doesn't work when viewing the readme as a diff. Can you try viewing the readme as a whole?
image

I can still turn it into a PNG, of course, but I think svgs are nicer. :)

**Comment by shibayan** [comment]
It seems to be a broken link in the diff view of PR. It doesn't seem to be a problem if you merge it.

Thanks!

**Review by shibayan — APPROVED** [review]

**Comment by odegroot** [comment]
Thank you!

**Pull request merged**
